
# common to all servers

- hosts: all
  tasks:
    
    # example for java installation
    - win_chocolatey: name=jdk8
      when: ansible_os_family == "Windows"

# installed per product

- hosts: cloud-agents
  roles:
    - role: cloud-agent

# in this example postgres will be installed on
# the same machine as the server (not HA setup)
# reporter is installed on windows using choco

- hosts: cloud-servers

  tasks:
    - name: install postgres
      win_chocolatey: name=postgresql
      install_args:
        - '/Password:{{ db_password }}'
  roles:
    - role: cloud-server
      db_password: "{{ db_password }}"

- hosts: nvs
  roles:
    - role: nv

# in this example postgres will be installed on
# the same machine as the server (not HA setup)
# reporter is installed on windows using choco

- hosts: reporters

  tasks:
    - name: install postgres
      win_chocolatey: name=postgresql
      install_args:
        - '/Password:{{ db_password }}'
  roles:
    - role: reporter
      db_password: "{{ db_password }}"

- hosts: file-storages
  roles:
    - role: file-storage

- hosts: app-signers
  roles:
    - role: app-signer

- hosts: regional-proxys
  roles:
    - role: regional-proxy

- hosts: selenium-agents
  roles:
    - role: selenium-agent
