
- hosts: localhost 
  roles:
    
    - role: java8
    
    - role: postgres
      db_names: 
        - cloudserver
        - reporter
      db_password: 123

    - role: cloud-server
      db_password: 123
    
    - role: reporter
      db_password: 123
    
    - role: cloud-agent
    
    - role: file-storage
    
    - role: app-signer
    
    - role: regional-proxy
