
- src: git+https://github.com/ExperitestOfficial/ansible-role-cloud-server.git
  version: "12.12"
  name: cloud-server

- src: git+https://github.com/ExperitestOfficial/ansible-role-regional-proxy.git
  version: "12.12"
  name: regional-proxy

- src: git+https://github.com/ExperitestOfficial/ansible-role-cloud-emulator-host.git
  version: "12.12"
  name: cloud-emulator-host

- src: git+https://github.com/ExperitestOfficial/ansible-role-audioservice-cloudagent.git
  version: "12.12"
  name: audioservice-cloudagent

- src: git+https://github.com/ExperitestOfficial/ansible-role-cloud-agent.git
  version: "12.12"
  name: cloud-agent

- src: git+https://github.com/ExperitestOfficial/ansible-role-file-storage.git
  version: "12.12"
  name: file-storage

- src: git+https://github.com/ExperitestOfficial/ansible-role-app-signer.git
  version: "12.12"
  name: app-signer

- src: git+https://github.com/ExperitestOfficial/ansible-role-reporter.git
  version: "12.12"
  name: reporter

- src: git+https://github.com/ExperitestOfficial/ansible-role-cloud-nv.git
  version: "12.12"
  name: cloud-nv

- src: git+https://github.com/ExperitestOfficial/ansible-role-selenium-agent.git
  version: "12.12"
  name: selenium-agent 

- src: git+https://github.com/ExperitestOfficial/ansible-role-java8.git
  version: "12.12"
  name: java8

- src: git+https://github.com/ExperitestOfficial/ansible-role-disk-space-validator.git
  version: master
  name: disk-space-validator
